export const ActionTypes ={
    SET_PRODUCTS:'SET_PRODUCTS',
    SELECTED_PRODUCTS:'SELECTED_PRODUCTS',
    REMOVE_PRODUCTS:'REMOVE_PRODUCTS',
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    CLEAR_CART:'CLEAR_CART',
    LOAD_CART:'LOAD_CART',
    UPDATE_CART:'UPDATE_CART',
    UPDATE_CART_INCREASE:'UPDATE_CART_INCREASE',
    UPDATE_CART_DECREASE:'UPDATE_CART_DECREASE',
    PRICE:'PRICE',
    PRODUCT_COUNT:'PRODUCT_COUNT',
    SELECTED_PRODUCTS_BY_SEARCH:'SELECTED_PRODUCTS_BY_SEARCH',

}